# Generated by Django 4.1.4 on 2023-01-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_serino_urun_seri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='seri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.serino'),
        ),
    ]
