# Generated by Django 4.1.4 on 2023-02-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_odeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='Sepet',
            field=models.ManyToManyField(to='urunler.sepet'),
        ),
    ]
